language: java

sudo: false
dist: trusty

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12

after_success:
  - bash <(curl -s https://codecov.io/bash)

