name: Build and run tests
 
on: [push, pull_request]
 
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15 ]
    name: Java ${{ matrix.java }} run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn --batch-mode clean test
